#  Chapter7　NumPy的基础

- **7.1 NumPy 概要**
    - **7.1.1 何谓NumPy**
    - **7.1.2 体验NumPy的高性能处理**
<br><br>
- **7.2 NumPy 一维数组**
    - **7.2.1 import**
    - **7.2.2 一维数组**
    - **7.2.3 一维数组的计算**
    - **7.2.4 索引引用与切片**
    - **7.2.5 使用ndarray 的注意事项**
    - **7.2.6 view与copy**
    - **7.2.7 布尔索引的引用** 
    - **7.2.8 通用函数**
    - **7.2.9 集合函数**  
    - **7.2.10 随机数**
<br><br>
- **7.3 NumPy 二维数组**
    - **7.3.1 二维数组**
    - **7.3.2 索引引用与切片**
    - **7.3.3 axis**
    - **7.3.4 花式索引引用**
    - **7.3.5 转置矩阵**
    - **7.3.6 排序**
    - **7.3.7 矩阵计算**
    - **7.3.8 统计函数**
    - **7.3.9 广播**
<br><br>
- **附加习题**
- **综合附加习题**

## ●7.1 NumPy 概要

### ○7.1.1 何谓NumPy

这里没有样本

### ○7.1.2 体验NumPy的高性能处理

#### □习题


In [ ]:
# 对比要的软件库进行导入
import numpy as np
import time
from numpy.random import rand

# 行和列的大小
N = 150

# 对矩阵进行初始化
matA = np.array(rand(N, N))
matB = np.array(rand(N, N))
matC = np.array([[0] * N for _ in range(N)])

# 使用 Python 的列表进行计算

# 获取开始时间
start = time.time()

# 通过 for 语句实现矩阵的乘法运算
for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]

print("只用Python的基本功能进行计算的结果：%.2f[sec]" % float(time.time() - start))

# 使用 NumPy 进行计算

# 获得开始时间
start = time.time()

# 使用 NumPy 执行矩阵的乘法运算
matC = np.dot(matA, matB)

# 由于舍去了小数点后 2 位数之后的部分，因此 NumPy 显示为 0.00[sec]
print("通过NumPy进行加速运算的结果：%.2f[sec]" % float(time.time() - start))

**程序清单7.2：习题**

#### □参考答案（实际的秒数根据其执行的环境会大有不同）

In [1]:
# 对比要的软件库进行导入
import numpy as np
import time
from numpy.random import rand

# 行和列的大小
N = 150

# 对矩阵进行初始化
matA = np.array(rand(N, N))
matB = np.array(rand(N, N))
matC = np.array([[0] * N for _ in range(N)])

# 使用 Python 的列表进行计算

# 获得开始时间
start = time.time()

# 通过 for 语句实现矩阵的乘法运算
for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]

print("只用 Python 的基本功能进行计算的结果：%.2f[sec]" % float(time.time() - start))

# 使用 NumPy 进行计算

# 获得开始时间
start = time.time()

# 使用 NumPy 执行矩阵的乘法运算
matC = np.dot(matA, matB)

# 由于舍去了小数点后 2 位数之后的部分，因此 NumPy 显示为 0.00[sec]
print("通过NumPy进行加速运算的结果：%.2f[sec]" % float(time.time() - start))

只用 Python 的基本功能进行计算的结果：3.20[sec]
通过NumPy进行加速运算的结果：0.32[sec]


**程序清单7.2：参考答案**

## ○7.2 NumPy 一维数组

### □7.2.1 import

#### □习题

In [ ]:
# 请导入 NumPy 库



**程序清单7.3：习题**

#### □参考答案

In [2]:
# 请导入 NumPy 库
import numpy as np

**程序清单7.4：参考答案**

### ○7.2.2 一维数组

#### □习题

In [ ]:
import numpy as np

storages = [24, 3, 4, 23, 10, 12]
print(storages)

# 请生成 ndarray 数组，并将其代入变量 np_storages 中


# 请对变量 np_storages 的类型进行输出
print()

**程序清单7.5：习题**

#### □参考答案

In [3]:
import numpy as np

storages = [24, 3, 4, 23, 10, 12]
print(storages)

# 请生成 ndarray 数组，并将其代入变量 np_storages 中
np_storages = np.array(storages)

# 请对变量 np_storages 的类型进行输出
print(type(np_storages))

[24, 3, 4, 23, 10, 12]
<class 'numpy.ndarray'>


**程序清单7.6：参考答案**

### ○7.2.3 一维数组的计算

In [5]:
# 请在不使用 NumPy 的条件下实现
storages = [1, 2, 3, 4]
new_storages = []
for n in storages:
    n += n
    new_storages.append(n)
print(new_storages)

[2, 4, 6, 8]


**程序清单7.7：一维数组的计算示例①**

In [6]:
# 使用 NumPy 实现
import numpy as np
storages = np.array([1, 2, 3, 4])
storages += storages
print(storages)

[2 4 6 8]


**程序清单 7.8：一维数组的计算示例②**

#### □习题


In [ ]:
import numpy as np

arr = np.array([2, 5, 3, 4, 8])

# arr + arr
print()

# arr - arr
print()

# arr ** 3
print()

# 1 / arr
print()

**程序清单7.9：习题**

#### □参考答案

In [7]:
import numpy as np

arr = np.array([2, 5, 3, 4, 8])

# arr + arr
print('arr + arr')
print(arr + arr)
print()

# arr - arr
print('arr - arr')
print(arr - arr)
print()

# arr ** 3
print('arr ** 3')
print(arr ** 3)
print()

# 1 / arr
print('1 / arr')
print(1 / arr)
print()

arr + arr
[ 4 10  6  8 16]

arr - arr
[0 0 0 0 0]

arr ** 3
[  8 125  27  64 512]

1 / arr
[0.5        0.2        0.33333333 0.25       0.125     ]



**程序清单7.10：参考答案**

### ○7.2.4 索引引用与切片

In [8]:

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


**程序清单7.11：切片的示例①**　

In [12]:
arr = np.arange(10)
arr[0:3] = 1
print(arr)

[1 1 1 3 4 5 6 7 8 9]


**程序清单7.12：切片的示例②**

#### □习题

In [ ]:
import numpy as np

arr = np.arange(10)
print(arr)

# 请将变量 arr 中的 3、 4、 5 这几个元素单独进行输出
print()

# 请将变量 arr 中的元素 3、 4、 5 更改为 24

print(arr)

**程序清单7.13：习题**

#### □参考答案

In [9]:
import numpy as np

arr = np.arange(10)
print(arr)

# 请将变量 arr 中的 3、 4、 5 这几个元素单独进行输出
print(arr[3:6])

# 请将变量 arr 中的元素 3、 4、 5 更改为 24
arr[3:6] = 24
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[ 0  1  2 24 24 24  6  7  8  9]


**程序清单7.14：参考答案**

### ○7.2.5 使用ndarray 的注意事项

#### □习题


In [ ]:
import numpy as np

# 观察将 ndarray 直接代入其他变量时的变化
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1
arr2[0] = 100

# 更改了其他变量之后，原始的变量也受到了影响
print(arr1)

# 观察使用 copy() 后，将 ndarray 代入其他变量时的变化
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1.copy()
arr2[0] = 100

# 更改了其他变量之后，原始的变量没有受到影响
print(arr1)

**程序清单7.15：习题**

#### □参考答案

In [10]:
import numpy as np

# 观察将 ndarray 直接代入其他变量时的变化
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1
arr2[0] = 100

# 更改了其他变量之后，原始的变量也受到了影响
print(arr1)

# 观察使用 copy() 后，将 ndarray 代入其他变量时的变化
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1.copy()
arr2[0] = 100

# 更改了其他变量之后，原始的变量没有受到影响
print(arr1)

[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]
[1 2 3 4 5]


**程序清单7.16：参考答案**

### ○7.2.6 view与copy

#### □习题


In [ ]:
import numpy as np

# 观察在 Python 的列表中使用切片时程序的行为
arr_List = [x for x in range(10)]
print("列表类型的数据")
print("arr_List:",arr_List)

print()
arr_List_copy = arr_List[:]
arr_List_copy[0] = 100


print("因为列表的切片是对数据进行复制而成的，所以在 arr_List 中不会反映出 arr_List_copy 中的变化")
print("arr_List:",arr_List)
print()

# 观察在 NumPy 的 ndarray 中使用切片时程序的行为
arr_NumPy = np.arange(10)
print("NumPy的ndarray数据")
print("arr_NumPy:",arr_NumPy)
print()

arr_NumPy_view = arr_NumPy[:]
arr_NumPy_view[0] = 100

print("NumPy 的切片会将 view ( 保存数据的地址信息 ) 代入，对 arr_NumPy_view 的变更将在 arr_NumPy 中被反映出来")
print("arr_NumPy:",arr_NumPy)
print()

# NumPyのndarrayでcopy()を用いた場合での挙動を確認しましょう
arr_NumPy = np.arange(10)
print('NumPyのndarrayでcopy()を用いた場合での挙動です')
print("arr_NumPy:",arr_NumPy)
print()
arr_NumPy_copy = arr_NumPy[:].copy()
arr_NumPy_copy[0] = 100

print("copy()を用いた場合は、コピーが生成されているのでarr_NumPy_copyはarr_NumPyに影響を与えません")
print("arr_NumPy:",arr_NumPy)

**程序清单7.17：习题**

#### □参考答案

In [1]:
import numpy as np

# 观察在 Python 的列表中使用切片时程序的行为
arr_List = [x for x in range(10)]
print("列表类型的数据")
print("arr_List:",arr_List)

print()
arr_List_copy = arr_List[:]
arr_List_copy[0] = 100

print("因为列表的切片是对数据进行复制而成的，所以在 arr_List 中不会反映出 arr_List_copy 中的变化")
print("arr_List:",arr_List)
print()

# 观察在 NumPy 的 ndarray 中使用切片时程序的行为
arr_NumPy = np.arange(10)
print("NumPy的ndarray数据")
print("arr_NumPy:",arr_NumPy)
print()

arr_NumPy_view = arr_NumPy[:]
arr_NumPy_view[0] = 100

print("NumPy 的切片会将 view ( 保存数据的地址信息 ) 代入，对 arr_NumPy_view 的变更将在 arr_NumPy 中被反映出来")
print("arr_NumPy:",arr_NumPy)
print()

# 观察在 NumPy 的 ndarray 中使用copy() 时程序的行为
arr_NumPy = np.arange(10)
print('在 NumPy 的 ndarray 中使用 copy() 的变化')
print("arr_NumPy:",arr_NumPy)
print()
arr_NumPy_copy = arr_NumPy[:].copy()
arr_NumPy_copy[0] = 100

print("使用 copy() 会生成备份，arr_NumPy_copy 不会对 arr_NumPy 造成影响")
print("arr_NumPy:",arr_NumPy)

列表类型的数据
arr_List: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

因为列表的切片是对数据进行复制而成的，所以在 arr_List 中不会反映出 arr_List_copy 中的变化
arr_List: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

NumPy的ndarray数据
arr_NumPy: [0 1 2 3 4 5 6 7 8 9]

NumPy 的切片会将 view ( 保存数据的地址信息 ) 代入，对 arr_NumPy_view 的变更将在 arr_NumPy 中被反映出来
arr_NumPy: [100   1   2   3   4   5   6   7   8   9]

在 NumPy 的 ndarray 中使用 copy() 的变化
arr_NumPy: [0 1 2 3 4 5 6 7 8 9]

使用 copy() 会生成备份，arr_NumPy_copy 不会对 arr_NumPy 造成影响
arr_NumPy: [0 1 2 3 4 5 6 7 8 9]


**程序清单7.18：参考答案**

### ○7.2.7 布尔索引的引用

In [13]:
arr = np.array([2, 4, 6, 7]) 
print(arr[np.array([True, True, True, False])])  

[2 4 6]


**程序清单7.19：布尔索引引用的示例①**

In [16]:
arr = np.array([2, 4, 6, 7]) 
print(arr[arr % 3 == 1])

[4 7]


**程序清单7.20：布尔索引引用的示例②**

#### □习题


In [ ]:
import numpy as np

arr = np.array([2, 3, 4, 5, 6, 7])

# 请对表示变量 arr 的各个元素是否能被 2 整除的布尔值的数组进行输出
print()

# 请对变量 arr 各个元素中能被 2 整除的元素所组成的数组进行输出
print()

**程序清单7.21：习题**

#### □参考答案

In [17]:
import numpy as np

arr = np.array([2, 3, 4, 5, 6, 7])

# 请对表示变量 arr 的各个元素是否能被 2 整除的布尔值的数组进行输出
print(arr % 2 == 0)

# 请对变量 arr 各个元素中能被 2 整除的元素所组成的数组进行输出
print(arr[arr % 2 == 0])

[ True False  True False  True False]
[2 4 6]


**程序清单7.22：参考答案**

### ○7.2.8 通用函数

#### □习题


In [ ]:
import numpy as np

arr = np.array([4, -9, 16, -4, 20])
print(arr)

# 请将变量 arr 中的各个元素转换成绝对值并代入变量 arr_abs 中
arr_abs = 
print(arr_abs)

# 请对变量 arr_abs 的各个元素的 e 的幂和平方根进行输出
print()
print()

**程序清单7.23：习题**

#### □参考答案

In [18]:
import numpy as np

arr = np.array([4, -9, 16, -4, 20])
print(arr)

# 请将变量 arr 中的各个元素转换成绝对值并代入变量 arr_abs 中
arr_abs = np.abs(arr)
print(arr_abs)

# 请对变量 arr_abs 的各个元素的 e 的幂和平方根进行输出
print(np.exp(arr_abs))
print(np.sqrt(arr_abs))

[ 4 -9 16 -4 20]
[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]


**程序清单7.24：参考答案**

### ○7.2.9 集合函数

#### □习题


In [ ]:
import numpy as np

arr1 = [2, 5, 7, 9, 5, 2]
arr2 = [2, 5, 8, 3, 1]

# 请使用 np.unique() 函数，将变量 arr1 中重复的元素去除之后的数组代入变量 new_arr1 中
new_arr1 = 
print(new_arr1)

# 请对变量 new_arr1 和变量 arr2 的并集进行输出
print()

# 请对变量 new_arr1 和变量 arr2 的交集进行输出
print()

# 请对从变量 new_arr1 中减去变量 arr2 的差集进行输出
print()

**程序清单7.25：习题**

#### □参考答案

In [19]:
import numpy as np

arr1 = [2, 5, 7, 9, 5, 2]
arr2 = [2, 5, 8, 3, 1]

# 请使用 np.unique() 函数，将变量 arr1 中重复的元素去除之后的数组代入变量 new_arr1 中
new_arr1 = np.unique(arr1)
print(new_arr1)

# 请对变量 new_arr1 和变量 arr2 的并集进行输出
print(np.union1d(new_arr1, arr2))

# 请对变量 new_arr1 和变量 arr2 的交集进行输出
print(np.intersect1d(new_arr1, arr2))

# 请对从变量 new_arr1 中减去变量 arr2 的差集进行输出
print(np.setdiff1d(new_arr1, arr2))

[2 5 7 9]
[1 2 3 5 7 8 9]
[2 5]
[7 9]


**程序清单7.26：解答**

### ○7.2.10 随机数

#### □习题


In [ ]:
import numpy as np

# 请在不需要添加 np.random 的方式下导入 randint() 函数


# 请将各元素大于 0 小于 10 的整数的矩阵 (5 × 2) 代入变量 arr1 中
arr1 = 
print(arr1)

# 请将 3 个 0~1 均匀分布的随机数代入变量 arr2 中
arr2 = 
print(arr2)

**程序清单7.27：习题**

#### □参考答案（输出结果可能和实际界面有所不同）

In [20]:
import numpy as np

# 请在不需要添加 np.random 的方式下导入 randint() 函数
from numpy.random import randint

# 请将各元素大于 0 小于 10 的整数的矩阵 (5 × 2) 代入变量 arr1 中
arr1 = randint(0, 11, (5, 2))
print(arr1)

# 请将 3 个 0~1 均匀分布的随机数代入变量 arr2 中
arr2 = np.random.rand(3)
print(arr2)

[[6 7]
 [0 6]
 [9 5]
 [4 8]
 [7 7]]
[0.63789953 0.25708531 0.05888615]


**程序清单7.28：参考答案**

## ●7.3 NumPy 二维数组

### ○7.3.1 二维数组

#### □习题


In [ ]:
import numpy as np

# 请将二维数组代入变量 arr 中
arr = 
print(arr)

# 请对变量 arr 的矩阵中的各个维度的元素数量进行输出
print()

# 请将变量 arr 转换成 4 行 2 列的矩阵
print()

**程序清单 7.29：习题**

#### □参考答案

In [21]:
import numpy as np

# 请将二维数组代入变量 arr 中
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

# 请对变量 arr 的矩阵中的各个维度的元素数量进行输出
print(arr.shape)

# 请将变量 arr 转换成 4 行 2 列的矩阵
print(arr.reshape(4, 2))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**程序清单7.30：参考答案**

### ○7.3.2 索引引用与切片

In [22]:
arr = np.array([[1, 2 ,3], [4, 5, 6]])
print(arr[1])

[4 5 6]


**程序清单7.31：索引引用的示例①**

In [23]:
arr = np.array([[1, 2 ,3], [4, 5, 6]])
print(arr[1,2])

6


**程序清单7.32：索引引用的示例②**

In [24]:
# 程序清单7.33
arr = np.array([[1, 2 ,3], [4, 5, 6]])
print(arr[1,1:])

[5 6]


**程序清单7.33：切片的示例**

#### □习题


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

# 请对变量 arr 中的元素 3 进行输出
print()

# 请从变量 arr 中取出指定的数组并进行输出
print()

**程序清单7.34：习题**

#### □参考答案

In [25]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

# 请对变量 arr 中的元素 3 进行输出
print(arr[0, 2])

# 请从变量 arr 中取出指定的数组并进行输出
# 下面取出的是“第 1 行之后的行”和“到第 2 列为止”的数组
print(arr[1:, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[[4 5]
 [7 8]]


**程序清单7.35：参考答案**

### ○7.3.3 axis

In [26]:
arr = np.array([[1, 2 ,3], [4, 5, 6]])

print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

21
[5 7 9]
[ 6 15]


**程序清单7.36：axis 的示例**

#### □习题


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 12], [15, 20, 22]])

# 请对 arr 的行的合计值进行求解，并返回如习题中所示的数组
print()

**程序清单7.37：习题**

#### □参考答案

In [27]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 12], [15, 20, 22]])

# 请对 arr 的行的合计值进行求解，并返回如习题中所示的数组
print(arr.sum(axis=1))

[ 6 21 57]


**程序清单7.38：参考答案**

### ○7.3.4 花式索引引用

In [28]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]]) 

# 按照第 3 行、第 2 行、第 0 行的顺序将行数据取出，并生成新的元素
# 索引编号从 0 开始
print(arr[[3, 2, 0]]) 

[[7 8]
 [5 6]
 [1 2]]


**程序清单7.39：花式索引引用的示例**

#### □习题


In [ ]:
import numpy as np

arr = np.arange(25).reshape(5, 5)

# 请对变量 arr 中的行的顺序进行更改并输出结果
print()

**程序清单7.40：习题**

#### □参考答案

In [28]:
import numpy as np

arr = np.arange(25).reshape(5, 5)

# 请对变量 arr 中的行的顺序进行更改并输出结果
print(arr[[1, 3, 0]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


**程序清单7.41：参考答案**

### ○7.3.5 转置矩阵

#### □习题


In [ ]:
import numpy as np

arr = np.arange(10).reshape(2, 5)

# 请将变量 arr 进行转置
print()

**程序清单7.42：习题**

#### □参考答案

In [29]:
import numpy as np

arr = np.arange(10).reshape(2, 5)

# 请将变量 arr 进行转置
print(arr.T) # print(np.transpose(arr))

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


**程序清单7.43：参考答案**

### ○7.3.6 排序

In [29]:
arr = np.array([15, 30, 5])
arr.argsort()

array([2, 0, 1], dtype=int64)

**程序清单7.44：排序的示例**

#### □习题


In [ ]:
import numpy as np

arr = np.array([[8, 4, 2], [3, 5, 1]])

# 请使用 argsort() 方法对变量arr进行排序并对结果进行输出
print()

# 请使用 np.sort() 函数对变量arr进行排序并对结果进行输出
print()

# 请使用 sort() 方法将变量arr按行进行排序

print(arr)

**程序清单7.45：习题**

#### □参考答案

In [30]:
import numpy as np

arr = np.array([[8, 4, 2], [3, 5, 1]])

# 请使用 argsort() 方法对变量arr进行排序并对结果进行输出
print(arr.argsort())

# 请使用 np.sort() 函数对变量arr进行排序并对结果进行输出
print(np.sort(arr))

# 请使用 sort() 方法将变量arr按行进行排序
arr.sort(1)
print(arr)

[[2 1 0]
 [2 0 1]]
[[2 4 8]
 [1 3 5]]
[[2 4 8]
 [1 3 5]]


**程序清单7.46：参考答案**　

### ○7.3.7 矩阵计算

#### □习题


In [ ]:
import numpy as np

# 对 arr 进行定义
arr = np.arange(9).reshape(3, 3)

# 请对变量 arr 与 arr 的矩阵乘积进行输出
print()

# 对 vec 进行定义
vec = arr.reshape(9)

# 请对变量 vec 的范数进行输出
print()

**程序清单7.47：习题**

#### □参考答案

In [31]:
import numpy as np

# 对 arr 进行定义
arr = np.arange(9).reshape(3, 3)

# 请对变量 arr 与 arr 的矩阵乘积进行输出
print(np.dot(arr, arr))

# 对 vec 进行定义
vec = arr.reshape(9)

# 请对变量 vec 的范数进行输出
print(np.linalg.norm(vec))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
14.2828568570857


**程序清单7.48：参考答案**

### ○7.3.8 统计函数

#### □习题


In [ ]:
import numpy as np

arr = np.arange(15).reshape(3, 5)

# 请对变量 arr 中每一列的平均值进行输出
print()

# 请对变量 arr 中行的合计值进行输出
print()

# 请对变量 arr 的最小值进行输出
print()

# 请对变量 arr 每一列中最大值的索引编号进行输出
print()

**程序清单7.49：习题**

#### □参考答案

In [31]:
import numpy as np

arr = np.arange(15).reshape(3, 5)

# 请对变量 arr 中每一列的平均值进行输出
print(arr.mean(axis=0))

# 请对变量 arr 中行的合计值进行输出
print(arr.sum(axis=1))

# 请对变量 arr 的最小值进行输出
print(arr.min())

# 请对变量 arr 每一列中最大值的索引编号进行输出
print(arr.argmax(axis=0))

[5. 6. 7. 8. 9.]
[10 35 60]
0
[2 2 2 2 2]


**程序清单 7.50：参考答案**

### ○7.3.9 广播

In [34]:
x = np.arange(6).reshape(2, 3)
print(x + 1)

[[1 2 3]
 [4 5 6]]


**程序清单7.51：广播的示例**

#### □习题

In [ ]:
import numpy as np



# 请生成包含从 0 到 14 的整数值的 3 × 5 的 ndarray 数组 x
x = np.arange(15).reshape(3, 5)

# 请生成包含从 0 到 4 的整数值的 1 × 5 的 ndarray 数组 y
y = np.array([np.arange(5)])

# 请从数组 x 的第 n 个列的所有行中减去 n
z = 

# 对 z 进行输出
print(z)

**程序清单7.52：习题**

#### □参考答案

In [35]:
import numpy as np


# 请生成包含从 0 到 14 的整数值的 3 × 5 的 ndarray 数组 x
x = np.arange(15).reshape(3, 5)

# 请生成包含从 0 到 4 的整数值的 1 × 5 的 ndarray 数组 y
y = np.array([np.arange(5)])

# 请从数组 x 的第 n 个列的所有行中减去 n
z = x - y

# 对 z 进行输出
print(z)

[[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]


**程序清单 7.53：参考答案**

## ●7.3 附加习题

#### □习题


In [ ]:
import numpy as np


np.random.seed(100)

# 请将各元素为 0~30 的整数的矩阵（5 × 3）代入变量 arr 中

print(arr)

# 请对变量 arr 进行转置

print(arr)

# 请将变量 arr 的 2、 3、 4 列中的矩阵 (3 × 3) 代入变量 arr1 中

print(arr1)

# 请使用行对变量 arr1 进行排序

print(arr1)

# 请对每一列的平均值进行输出



**程序清单7.54：习题**

#### □参考答案

In [32]:
import numpy as np


np.random.seed(100)

# 请将各元素为 0~30 的整数的矩阵（5 × 3）代入变量 arr 中
arr = np.random.randint(0, 31, (5, 3))
print(arr)

# 请对变量 arr 进行转置
arr = arr.T
print(arr)

# 请将变量 arr 的 2、 3、 4 列中的矩阵 (3 × 3) 代入变量 arr1 中
arr1 = arr[:, 1:4]
print(arr1)

# 请使用行对变量 arr1 进行排序
arr1.sort(0)
print(arr1)

# 请对每一列的平均值进行输出
print(arr1.mean(axis = 0))

[[ 8 24  3]
 [ 7 23 15]
 [16 10 30]
 [20  2 21]
 [ 2  2 14]]
[[ 8  7 16 20  2]
 [24 23 10  2  2]
 [ 3 15 30 21 14]]
[[ 7 16 20]
 [23 10  2]
 [15 30 21]]
[[ 7 10  2]
 [15 16 20]
 [23 30 21]]
[15.         18.66666667 14.33333333]


**程序清单7.55：参考答案**

# ●综合附加习题

### □习题

In [ ]:
import numpy as np

# 对随机数进行初始化处理
np.random.seed(0)

# 根据所指定的宽度和高度使用随机数来生成图像的函数
def make_image(m, n):
    
    # 请对 n × m 数组的各个元素使用 0~5 之间的随机值进行填充

    
    return image


# 对指定的矩阵的一部分内容进行变更的函数
def change_little(matrix):
    # 请获取所指定矩阵的形状，并将其代入 shape 中

    
    # 对于矩阵中的各个元素，随机地决定是否对其进行变更
    # 如果进行变更的话，请对 0~5 中的任意一个整数进行随机的替换
    
    
    
    
    return matrix

# 随机的生成图像
image1 = make_image(3, 3)
print(image1)
print()

# 随机的应用变更
image2 = change_little(np.copy(image1))
print(image2)
print()

# 请计算 image1 和 image2 的差分，并将结果代入 image3 中

print(image3)
print()

# 请计算 image3 中各元素的绝对值，并将其再次代入 image3 中


# 对 image3 进行输出
print(image3)

**程序清单7.56：习题**

###  □参考答案

In [33]:
import numpy as np

# 对随机数进行初始化处理
np.random.seed(0)

# 根据所指定的宽度和高度使用随机数来生成图像的函数
def make_image(m, n):
    
    # 请对 n × m 数组的各个元素使用 0~5 之间的随机值进行填充
    image = np.random.randint(0, 6, (m, n))
        
    return image

# 对指定的矩阵的一部分内容进行变更的函数
def change_little(matrix):
    # 请获取所指定矩阵的形状，并将其代入 shape 中
    shape = matrix.shape
    
    # 对于矩阵中的各个元素，随机地决定是否对其进行变更
    # 如果进行变更的话，请对 0~5 中的任意一个整数进行随机的替换
    for i in range(shape[0]):
        for j in range(shape[1]):
            if np.random.randint(0, 2)==1:
                matrix[i][j] = np.random.randint(0, 6, 1)
    return matrix

# 随机的生成图像
image1 = make_image(3, 3)
print(image1)
print()

# 随机的应用变更
image2 = change_little(np.copy(image1))
print(image2)
print()

# 请计算 image1 和 image2 的差分，并将结果代入 image3 中
image3 = image2 - image1
print(image3)
print()

# 请计算 image3 中各元素的绝对值，并将其再次代入 image3 中
image3 = np.abs(image3)

# 对 image3 进行输出
print(image3)

[[4 5 0]
 [3 3 3]
 [1 3 5]]

[[4 5 0]
 [3 3 3]
 [0 5 5]]

[[ 0  0  0]
 [ 0  0  0]
 [-1  2  0]]

[[0 0 0]
 [0 0 0]
 [1 2 0]]


**程序清单7.57：参考答案**